<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="myMvnPro by groups" duration-ms="112732" started-at="2017-05-10T09:17:18Z" finished-at="2017-05-10T09:19:11Z">
    <groups>
      <group name="A1">
        <method signature="A1Dev1028UnitCreate.CreateData()[pri:0, instance:testcases.A1Dev1028UnitCreate@146ba0ac]" name="CreateData" class="testcases.A1Dev1028UnitCreate"/>
      </group> <!-- A1 -->
      <group name="A2">
        <method signature="A2Dev1072LoginFirstTime.logInChangePass(java.lang.String, java.lang.String)[pri:0, instance:testcases.A2Dev1072LoginFirstTime@754ba872]" name="logInChangePass" class="testcases.A2Dev1072LoginFirstTime"/>
      </group> <!-- A2 -->
    </groups>
    <test name="GRP-A1,A2" duration-ms="112732" started-at="2017-05-10T09:17:18Z" finished-at="2017-05-10T09:19:11Z">
      <class name="testcases.A2Dev1072LoginFirstTime">
        <test-method status="PASS" signature="start()[pri:0, instance:testcases.A2Dev1072LoginFirstTime@754ba872]" test-instance-name="" name="start" is-config="true" duration-ms="2202" started-at="2017-05-10T11:19:04Z" finished-at="2017-05-10T11:19:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method name="logInChangePass" test-instance-name="" signature="logInChangePass(java.lang.String, java.lang.String)[pri:0, instance:testcases.A2Dev1072LoginFirstTime@754ba872]" depends-on-groups="A1" status="SKIP" duration-ms="0" finished-at="2017-05-10T11:19:06Z" started-at="2017-05-10T11:19:06Z" data-provider="users">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method A2Dev1072LoginFirstTime.logInChangePass(java.lang.String, java.lang.String)[pri:0, instance:testcases.A2Dev1072LoginFirstTime@754ba872] depends on not successfully finished methods in group "A1"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method A2Dev1072LoginFirstTime.logInChangePass(java.lang.String, java.lang.String)[pri:0, instance:testcases.A2Dev1072LoginFirstTime@754ba872] depends on not successfully finished methods in group "A1"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInChangePass -->
        <test-method status="PASS" signature="stop()[pri:0, instance:testcases.A2Dev1072LoginFirstTime@754ba872]" test-instance-name="" name="stop" is-config="true" duration-ms="5214" started-at="2017-05-10T11:19:06Z" finished-at="2017-05-10T11:19:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
      </class> <!-- testcases.A2Dev1072LoginFirstTime -->
      <class name="testcases.A1Dev1028UnitCreate">
        <test-method status="PASS" signature="start()[pri:0, instance:testcases.A1Dev1028UnitCreate@146ba0ac]" test-instance-name="" name="start" is-config="true" duration-ms="1997" started-at="2017-05-10T11:17:18Z" finished-at="2017-05-10T11:17:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="CreateData()[pri:0, instance:testcases.A1Dev1028UnitCreate@146ba0ac]" test-instance-name="" name="CreateData" duration-ms="98175" started-at="2017-05-10T11:17:20Z" finished-at="2017-05-10T11:18:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcases.A1Dev1028UnitCreate.CreateData(A1Dev1028UnitCreate.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateData -->
        <test-method status="PASS" signature="stop()[pri:0, instance:testcases.A1Dev1028UnitCreate@146ba0ac]" test-instance-name="" name="stop" is-config="true" duration-ms="5129" started-at="2017-05-10T11:18:59Z" finished-at="2017-05-10T11:19:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
      </class> <!-- testcases.A1Dev1028UnitCreate -->
    </test> <!-- GRP-A1,A2 -->
  </suite> <!-- myMvnPro by groups -->
</testng-results>
