<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mbpro-dejuan.local" name="testcases.B2Dev1000OptionPush" tests="9" failures="1" timestamp="7 Sep 2016 07:16:53 GMT" time="225.613" errors="0">
  <testcase name="campaignAddAll" time="9.823" classname="testcases.B2Dev1000OptionPush"/>
  <testcase name="CheckStatus" time="23.948" classname="testcases.B2Dev1000OptionPush">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [3] but found [2]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcases.B2Dev1000OptionPush.CheckStatus(B2Dev1000OptionPush.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- CheckStatus -->
  <testcase name="optionPush" time="35.005" classname="testcases.B2Dev1000OptionPush"/>
  <testcase name="notificationNoCampaignDeselect" time="20.796" classname="testcases.B2Dev1000OptionPush"/>
  <testcase name="optionPush" time="34.622" classname="testcases.B2Dev1000OptionPush"/>
  <testcase name="optionPush" time="53.182" classname="testcases.B2Dev1000OptionPush"/>
  <testcase name="deletAnOffer" time="4.612" classname="testcases.B2Dev1000OptionPush"/>
  <testcase name="campaignAddOne" time="6.418" classname="testcases.B2Dev1000OptionPush"/>
  <testcase name="optionPush" time="37.207" classname="testcases.B2Dev1000OptionPush"/>
</testsuite> <!-- testcases.B2Dev1000OptionPush -->
