<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mbpro-dejuan.local" name="testcases.D6Dev0000PlusPMB" tests="6" failures="0" timestamp="25 Nov 2016 14:44:46 GMT" time="71.869" errors="5">
  <testcase name="BuyMultiplePPPAndBuyAndGetOrderOverview" time="0.000" classname="testcases.D6Dev0000PlusPMB">
    <error type="java.lang.Throwable" message="Method D6Dev0000PlusPMB.BuyMultiplePPPAndBuyAndGetOrderOverview()[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group &quot;D5&quot;">
      <![CDATA[java.lang.Throwable: Method D6Dev0000PlusPMB.BuyMultiplePPPAndBuyAndGetOrderOverview()[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group "D5"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- BuyMultiplePPPAndBuyAndGetOrderOverview -->
  <testcase name="setPPPricesByPublisher" time="0.000" classname="testcases.D6Dev0000PlusPMB">
    <error type="java.lang.Throwable" message="Method D6Dev0000PlusPMB.setPPPricesByPublisher()[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group &quot;D5&quot;">
      <![CDATA[java.lang.Throwable: Method D6Dev0000PlusPMB.setPPPricesByPublisher()[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group "D5"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- setPPPricesByPublisher -->
  <testcase name="AddInventoriesToMyLots" time="71.869" classname="testcases.D6Dev0000PlusPMB"/>
  <testcase name="MBGetOrderOverview" time="0.000" classname="testcases.D6Dev0000PlusPMB">
    <error type="java.lang.Throwable" message="Method D6Dev0000PlusPMB.MBGetOrderOverview()[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group &quot;D5&quot;">
      <![CDATA[java.lang.Throwable: Method D6Dev0000PlusPMB.MBGetOrderOverview()[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group "D5"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- MBGetOrderOverview -->
  <testcase name="BuySinglePPP" time="0.000" classname="testcases.D6Dev0000PlusPMB">
    <error type="java.lang.Throwable" message="Method D6Dev0000PlusPMB.BuySinglePPP()[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group &quot;D5&quot;">
      <![CDATA[java.lang.Throwable: Method D6Dev0000PlusPMB.BuySinglePPP()[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group "D5"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- BuySinglePPP -->
  <testcase name="checkFinalOrderResults" time="0.000" classname="testcases.D6Dev0000PlusPMB">
    <error type="java.lang.Throwable" message="Method D6Dev0000PlusPMB.checkFinalOrderResults(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group &quot;D5&quot;">
      <![CDATA[java.lang.Throwable: Method D6Dev0000PlusPMB.checkFinalOrderResults(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.D6Dev0000PlusPMB@4f7d0008] depends on not successfully finished methods in group "D5"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- checkFinalOrderResults -->
</testsuite> <!-- testcases.D6Dev0000PlusPMB -->
