<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mbpro-dejuan.lan" name="testcases.C5Dev1101MBBuyCheckOrders" tests="6" failures="1" timestamp="24 Nov 2016 20:55:21 GMT" time="109.931" errors="0">
  <testcase name="checkOrderValue" time="0.001" classname="testcases.C5Dev1101MBBuyCheckOrders"/>
  <testcase name="checkOrderValue" time="0.000" classname="testcases.C5Dev1101MBBuyCheckOrders"/>
  <testcase name="checkOrderValue" time="0.002" classname="testcases.C5Dev1101MBBuyCheckOrders">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [01-12-2016] but found [30-11-2016]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [01-12-2016] but found [30-11-2016]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcases.C5Dev1101MBBuyCheckOrders.checkOrderValue(C5Dev1101MBBuyCheckOrders.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- checkOrderValue -->
  <testcase name="compareOrdersPubSideAndMBSide" time="0.006" classname="testcases.C5Dev1101MBBuyCheckOrders"/>
  <testcase name="fatchOrders" time="41.840" classname="testcases.C5Dev1101MBBuyCheckOrders"/>
  <testcase name="SelectCmpBuyTwoTogether" time="68.082" classname="testcases.C5Dev1101MBBuyCheckOrders"/>
</testsuite> <!-- testcases.C5Dev1101MBBuyCheckOrders -->
